name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
#     - name: rust-clippy-check
#       uses: actions-rs/clippy-check@v1.0.5
#       with:
#         token: ${{ secrets.GITHUB_TOKEN }}
#         name: clippy-check
#         args: --all-features
    - name: rust-audit-check
      uses: actions-rs/audit-check@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: rust-clippy-check
        uses: actions-rs/clippy-check@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: clippy-check
