name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: rust-grcov
      uses: actions-rs/grcov@v0.1.4
      # with:
        # Path to the configuration file (optional, relative to the repository root)
        # config: # optional, default is .github/actions-rs/grcov.yml
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.5
